# Workflow for deploying master branch to GitHub Pages
name: Deploy master branch to Pages

on:
  push:
    branches:
      - master

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: master-logic-web # More meaningful name for the environment
      url: ${{ steps.deploy_master.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact for master branch
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.' # Upload the entire repository to retain the folder structure

      - name: Deploy to GitHub Pages
        id: deploy_master
        uses: actions/deploy-pages@v2
