# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  push:
    branches:
      - master
      - develop

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deploy_master.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact for master branch
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.' # Upload the entire repository to retain the folder structure

      - name: Upload artifact for develop branch
        if: github.ref == 'refs/heads/develop'
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'
          retention-days: 1

      - name: Deploy to GitHub Pages (master)
        if: github.ref == 'refs/heads/master'
        id: deploy_master
        uses: actions/deploy-pages@v2

      - name: Deploy to GitHub Pages (develop)
        if: github.ref == 'refs/heads/develop'
        id: deploy_develop
        uses: actions/deploy-pages@v2
        with:
          branch: gh-pages # Target branch for GitHub Pages
          path: dev # Subdirectory for the develop branch
