# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  push:
    branches:
      - master
      - develop

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact for master branch
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'Build' # Path to your build output directory

      - name: Upload artifact for develop branch
        if: github.ref == 'refs/heads/develop'
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'Build'
          retention-days: 1

      - name: Deploy to GitHub Pages (master)
        if: github.ref == 'refs/heads/master'
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Deploy to GitHub Pages (develop)
        if: github.ref == 'refs/heads/develop'
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          branch: gh-pages # Target branch for GitHub Pages
          path: dev # Subdirectory for the develop branch
